### PR TITLE
Package skeleton

### PR DESCRIPTION
**Pull request by coatless**

### CODE REVIEW

**Comment by daviddalpiaz** [comment]
I'm going to delay merging this until next week as it will break a couple places where the data is currently being used in ongoing assignments.

**Comment by daviddalpiaz** [comment]
(I think? I haven't looked at it super closely, but I saw some changes to the folder structure.)

**Comment by coatless** [comment]
@daviddalpiaz let's do it like this:

- Create the `dalpiaz` repository. I'll move this over there.
- We'll establish a submodule to this repository inside of the `data-raw` portion.

**Comment by daviddalpiaz** [comment]
Let's add this to the meeting agenda.

**Pull request merged**
